language: node_js
node_js:
- 10
env:
  global:
    secure: rwTamVsIrxV5B03DLrTvggDq8MpHKvJv9CIHhz5bMl0j4dl07qtnrANR/LVD6JJHCmxrDBRI/a1dmDvwISuCXFbm3wU2q9z/HfPnWuA3r1TwW18LFzBbcMvAC+ViQ7wb9yePKfuPpWCvBYSZUCNyp/kEN95Ej8qQYQyie2EVSJf//il5yTjl10OSC/bLRYlrmbcquPAqN5ZXRtQpWyuUPyj3QOe3kKG147bKY5XSCpuwUgX26DQQemBz60W4g3ScV6a3efoacxYQLOdrou8jzNL7JnMAkVRcNA3+Yw9WSB5KM+OiADG4Lko316dGoJjl2Wd+5YFoXNXvjfWfATy9c9Rh2iRoHvSeaTJHrCy0P02hwehwwEyABipGJZXhQE8bfZYMtPK4DmFASHE56viOD4HZRz1YGcFkvcAH4l+b0vLLnsVoRmG252HCoKjnXO4gmTyQEN7bY7m+DakfYaK+URk+VeqpgrM+m+msGgggaCu7Y56648H1+/1Mjl+Fpghcdeb9vrSosZBionP3Fsx4ZAfE8XxXNkyHgNaGXIJZVSOuEi8Bm2jbRr2lbwMmUzchE1wcGr0mV7Ib3sF4OH7qT9dZ2UKL1LcDxlCny8n4o6ZRIdEom/94KT08svUTtDBh+ONjZGCgrg0dG3hsz2Vu+gFw2Cmayx5twry+/w9ARBg=

script:
  - sonar-scanner
