name: Deploy gh-pages

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on:
  release:
    types: [created]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      - run: rm .eslintrc package.json
      - run: yarn predeploy
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          email: mail@sandeshshrestha.com
          build_dir: example/build
