name: Deploy gh-pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      # - name: Clean parent
      #   run: rm .eslintrc package.json
      # - name: Build
      #   run: cd example && yarn install && yarn add react-user-guide && yarn build
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4.2.2
      #   with:
      #     branch: gh-pages
      #     folder: example/build
