name: Node.js Package and GH pages deploy

on:
  release:
    types: [created]

jobs:
  build-deploy-npm-package-and-ghpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Clean parent
        run: rm .eslintrc package.json
      - name: Build gh-pages
        run: cd example && yarn install && yarn add react-user-guide && yarn build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: example/build

